category_keywords = {
    "eat_and_drink": ["restaurant", "menu", "food", "dining", "cuisine", "bar", "cafe", "grill", "buffet", "drinks", "meals"],
    "accommodation": ["hotel", "motel", "hostel", "bnb", "lodging", "stay", "suite", "room", "resort"],
    "automotive": ["car", "vehicle", "repair", "auto", "mechanic", "garage", "dealership", "tire", "oil change"],
    "arts_and_entertainment": ["theater", "music", "concert", "gallery", "film", "comedy", "cinema", "stage", "performance"],
    "attractions_and_activities": ["amusement", "park", "zoo", "arcade", "adventure", "tourist", "landmark", "attraction"],
    "active_life": ["fitness", "gym", "yoga", "exercise", "outdoor", "sports", "recreation", "workout", "hiking", "skate"],
    "beauty_and_spa": ["spa", "salon", "nails", "massage", "facial", "waxing", "hair", "makeup", "beauty"],
    "education": ["school", "college", "university", "academy", "training", "course", "tutoring", "education", "student", "learning"],
    "financial_service": ["bank", "insurance", "finance", "atm", "account", "credit", "mortgage", "loan", "investment"],
    "private_establishments_and_corporates": ["corporate", "headquarters", "company", "business", "office", "enterprise", "hq"],
    "retail": ["store", "shop", "mall", "retail", "outlet", "boutique", "clothing", "grocery", "supermarket", "shopping"],
    "health_and_medical": ["clinic", "hospital", "doctor", "dentist", "medical", "healthcare", "nurse", "treatment", "surgery"],
    "pets": ["pet", "vet", "animal", "grooming", "boarding", "dog", "cat", "petcare", "kennel"],
    "business_to_business": ["supplier", "manufacturer", "wholesale", "b2b", "industrial", "distributor", "vendor"],
    "public_service_and_government": ["city", "county", "government", "dmv", "courthouse", "police", "fire", "public", "service"],
    "religious_organization": ["church", "temple", "mosque", "synagogue", "religious", "worship", "faith", "congregation"],
    "real_estate": ["real estate", "broker", "agent", "property", "housing", "apartment", "condo", "listing", "realtor"],
    "travel": ["airport", "flight", "travel", "tourism", "visa", "passport", "itinerary", "trip", "agency"],
    "mass_media": ["radio", "tv", "television", "media", "news", "magazine", "newspaper", "press", "station"],
    "home_service": ["plumbing", "electrician", "hvac", "appliance", "repair", "contractor", "cleaning", "maintenance"],
    "professional_services": ["consultant", "lawyer", "accountant", "notary", "therapy", "translation", "professional", "service"],
    "structure_and_geography": ["bridge", "mountain", "valley", "river", "park", "building", "monument", "landmark", "structure"]
}
